In [ ]:
import pandas as pd
import scipy.io as sio
import numpy as np
import datetime
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import re

upRiverDF = pd.read_csv('upriver_2012_2013_processed.csv', parse_dates = ['DN'])
upRiverDF['dayDN'] = upRiverDF['DN'].dt.floor('D')

dayDN = upRiverDF['dayDN'].drop_duplicates().to_list()
for dateMark in dayDN:
    if upRiverDF.loc[(upRiverDF['dayDN'] == dateMark) & (upRiverDF["SurfaceSalCorrected"] < 0.25)].shape[0] > 0:
        # since we have values lower than 0.25 salinity, we simply need to average those respective temperature values to find the river temperature 
        dailyRiverTemperature = np.nanmean(upRiverDF.loc[(upRiverDF['dayDN'] == dateMark) & (upRiverDF["SurfaceSalCorrected"] < 0.25)]["SurfaceTemp"])
    else:
        # we need to plot all daily values in T vs S plots, then creating linear regression plots, to find the y-intercept for each, which gives us the average daily river temperature

    print(dateMark, upRiverDF.loc[(upRiverDF['dayDN'] == dateMark) & (upRiverDF["SurfaceSalCorrected"] < 0.25)].shape)

2012-12-12 00:00:00 (18, 9)
2012-12-13 00:00:00 (196, 9)
2012-12-14 00:00:00 (192, 9)
2012-12-15 00:00:00 (183, 9)
2012-12-16 00:00:00 (177, 9)
2012-12-17 00:00:00 (256, 9)
2012-12-18 00:00:00 (288, 9)
2012-12-19 00:00:00 (288, 9)
2012-12-20 00:00:00 (288, 9)
2012-12-21 00:00:00 (288, 9)
2012-12-22 00:00:00 (288, 9)
2012-12-23 00:00:00 (288, 9)
2012-12-24 00:00:00 (288, 9)
2012-12-25 00:00:00 (288, 9)
2012-12-26 00:00:00 (288, 9)
2012-12-27 00:00:00 (288, 9)
2012-12-28 00:00:00 (288, 9)
2012-12-29 00:00:00 (288, 9)
2012-12-30 00:00:00 (288, 9)
2012-12-31 00:00:00 (288, 9)
2013-01-01 00:00:00 (288, 9)
2013-01-02 00:00:00 (273, 9)
2013-01-03 00:00:00 (234, 9)
2013-01-04 00:00:00 (252, 9)
2013-01-05 00:00:00 (250, 9)
2013-01-06 00:00:00 (186, 9)
2013-01-07 00:00:00 (171, 9)
2013-01-08 00:00:00 (185, 9)
2013-01-09 00:00:00 (146, 9)
2013-01-10 00:00:00 (230, 9)
2013-01-11 00:00:00 (246, 9)
2013-01-12 00:00:00 (246, 9)
2013-01-13 00:00:00 (228, 9)
2013-01-14 00:00:00 (228, 9)
2013-01-15 00:00:00 (222, 9)
2013-01-16 00:00:00 (229, 9)
2013-01-17 00:00:00 (206, 9)
2013-01-18 00:00:00 (200, 9)
2013-01-19 00:00:00 (179, 9)
2013-01-20 00:00:00 (123, 9)
2013-01-21 00:00:00 (11, 9)
2013-01-22 00:00:00 (0, 9)
2013-01-23 00:00:00 (0, 9)
2013-01-24 00:00:00 (0, 9)
2013-01-25 00:00:00 (0, 9)
2013-01-26 00:00:00 (0, 9)
2013-01-27 00:00:00 (38, 9)
2013-01-28 00:00:00 (209, 9)
2013-01-29 00:00:00 (274, 9)
2013-01-30 00:00:00 (288, 9)
2013-01-31 00:00:00 (288, 9)
2013-02-01 00:00:00 (279, 9)
2013-02-02 00:00:00 (267, 9)
2013-02-03 00:00:00 (254, 9)
2013-02-04 00:00:00 (250, 9)
2013-02-05 00:00:00 (171, 9)
2013-02-06 00:00:00 (116, 9)
2013-02-07 00:00:00 (34, 9)
2013-02-08 00:00:00 (118, 9)
2013-02-09 00:00:00 (172, 9)
2013-02-10 00:00:00 (138, 9)
2013-02-11 00:00:00 (126, 9)
2013-02-12 00:00:00 (111, 9)
2013-02-13 00:00:00 (143, 9)
2013-02-14 00:00:00 (160, 9)
2013-02-15 00:00:00 (166, 9)
2013-02-16 00:00:00 (155, 9)
2013-02-17 00:00:00 (181, 9)
2013-02-18 00:00:00 (98, 9)
2013-02-19 00:00:00 (9, 9)
2013-02-20 00:00:00 (0, 9)
2013-02-21 00:00:00 (0, 9)
2013-02-22 00:00:00 (0, 9)
2013-02-23 00:00:00 (94, 9)
2013-02-24 00:00:00 (267, 9)
2013-02-25 00:00:00 (230, 9)
2013-02-26 00:00:00 (226, 9)
2013-02-27 00:00:00 (200, 9)
2013-02-28 00:00:00 (180, 9)
2013-03-01 00:00:00 (232, 9)
2013-03-02 00:00:00 (237, 9)
2013-03-03 00:00:00 (251, 9)
2013-03-04 00:00:00 (238, 9)
2013-03-05 00:00:00 (110, 9)
2013-03-06 00:00:00 (56, 9)
2013-03-07 00:00:00 (67, 9)
2013-03-08 00:00:00 (212, 9)
2013-03-09 00:00:00 (214, 9)
2013-03-10 00:00:00 (170, 9)
2013-03-11 00:00:00 (152, 9)
2013-03-12 00:00:00 (146, 9)
2013-03-13 00:00:00 (141, 9)
2013-03-14 00:00:00 (134, 9)
2013-03-15 00:00:00 (121, 9)
2013-03-16 00:00:00 (155, 9)
2013-03-17 00:00:00 (200, 9)
2013-03-18 00:00:00 (180, 9)
2013-03-19 00:00:00 (77, 9)
2013-03-20 00:00:00 (0, 9)
2013-03-21 00:00:00 (83, 9)
2013-03-22 00:00:00 (288, 9)
2013-03-23 00:00:00 (288, 9)
2013-03-24 00:00:00 (252, 9)
2013-03-25 00:00:00 (215, 9)
2013-03-26 00:00:00 (185, 9)
2013-03-27 00:00:00 (147, 9)
2013-03-28 00:00:00 (131, 9)
2013-03-29 00:00:00 (115, 9)
2013-03-30 00:00:00 (117, 9)
2013-03-31 00:00:00 (73, 9)
2013-04-01 00:00:00 (74, 9)
2013-04-02 00:00:00 (107, 9)
2013-04-03 00:00:00 (102, 9)
2013-04-04 00:00:00 (71, 9)
2013-04-05 00:00:00 (39, 9)
2013-04-06 00:00:00 (103, 9)
2013-04-07 00:00:00 (228, 9)
2013-04-08 00:00:00 (288, 9)
2013-04-09 00:00:00 (287, 9)
2013-04-10 00:00:00 (235, 9)
2013-04-11 00:00:00 (231, 9)
2013-04-12 00:00:00 (217, 9)
2013-04-13 00:00:00 (217, 9)
2013-04-14 00:00:00 (206, 9)
2013-04-15 00:00:00 (230, 9)
2013-04-16 00:00:00 (251, 9)
2013-04-17 00:00:00 (258, 9)
2013-04-18 00:00:00 (262, 9)
2013-04-19 00:00:00 (251, 9)
2013-04-20 00:00:00 (257, 9)
2013-04-21 00:00:00 (230, 9)
2013-04-22 00:00:00 (215, 9)
2013-04-23 00:00:00 (186, 9)
2013-04-24 00:00:00 (150, 9)
2013-04-25 00:00:00 (97, 9)
2013-04-26 00:00:00 (68, 9)
2013-04-27 00:00:00 (30, 9)
2013-04-28 00:00:00 (30, 9)
2013-04-29 00:00:00 (21, 9)
2013-04-30 00:00:00 (58, 9)
2013-05-01 00:00:00 (116, 9)
2013-05-02 00:00:00 (119, 9)
2013-05-03 00:00:00 (95, 9)
2013-05-04 00:00:00 (32, 9)
2013-05-05 00:00:00 (8, 9)
2013-05-06 00:00:00 (0, 9)
2013-05-07 00:00:00 (0, 9)
2013-05-08 00:00:00 (0, 9)
2013-05-09 00:00:00 (0, 9)
2013-05-10 00:00:00 (0, 9)
2013-05-11 00:00:00 (0, 9)
2013-05-12 00:00:00 (0, 9)
2013-05-13 00:00:00 (0, 9)
2013-05-14 00:00:00 (0, 9)
2013-05-15 00:00:00 (0, 9)
2013-05-16 00:00:00 (0, 9)
2013-05-17 00:00:00 (0, 9)
2013-05-18 00:00:00 (0, 9)
2013-05-19 00:00:00 (0, 9)
2013-05-20 00:00:00 (0, 9)
2013-05-21 00:00:00 (0, 9)